### ISSUE TITLE
Students shouldn't be able to take the same exam twice

### ISSUE THREAD

**Issue by GeorgeHahn** [jflexlanoue/CS490#28]

**Comment by garykc** [comment]
Can you provide a boolean `submitted` to keep track of whether an exam has been taken already across sessions?

**Comment by GeorgeHahn** [comment]
It should be possible to check this by looking for results for a given
`studentid` and `examid`. See the backend docs for result retrieval.  

If that doesn't do it, just let me know what db table you'd like the
`submitted` field added
to.![](https://link.nylas.com/open/enum3e82sna310p5o9s7c0i2x/local-
f3a99126-7b52?r=cmVwbHkrMDAwN2FiZGJlYWZjMTRjNzBmMmQ3Y2RlMTBjNWJlNDc0M2FmZjY0MDM2MGY3Nzg2OTJjZjAwMDAwMDAxMTNiNTNlM2I5MmExNjljZTA5ZmI4NWRkQHJlcGx5LmdpdGh1Yi5jb20=)
