### ISSUE TITLE
Questions should be able to have constraints

### ISSUE THREAD

**Issue by GeorgeHahn** [jflexlanoue/CS490#43]
Checkbox for:
- Use a loop
- Use recursion

**Comment by garykc** [comment]
Can you elaborate? I'm not sure what you mean.

**Comment by GeorgeHahn** [comment]
Need a pair of checkboxes or radio buttons. One should be 'Requires recursion' the other 'Requires loop' or similar.

On Sat, Jul 30, 2016 at 12:42 AM -0400, "garykc" notifications@github.com wrote:

Can you elaborate?
