### ISSUE TITLE
Deleting exam messes up student results

### ISSUE THREAD

**Issue by garykc** [jflexlanoue/CS490#71]
Best to just see the [screenshot](http://imagizer.imageshack.com/img923/2787/hovKW3.png).

**Comment by GeorgeHahn** [comment]
Assign this to me, I'll fix it on the backend.

From: garykc

Sent: Friday, August 5, 12:07 AM

Subject: [jflexlanoue/CS490] Deleting exam messes up student results (#71)

To: jflexlanoue/CS490

Best to just see the screenshot.

**Comment by GeorgeHahn** [comment]
Closed by c0844e3c4f14ed77dfe338878fbf63e0f7814f02, ff561cf1dba91d2a459094b95f82037434842455
